using System;

namespace Microsoft.ServiceBus.Channels
{
	internal delegate ISingletonChannelListener SingletonPreambleDemuxCallback(ServerSingletonPreambleConnectionReader serverSingletonPreambleReader);
}