using System;
using System.Runtime.CompilerServices;
using System.Runtime.Serialization;

namespace Microsoft.ServiceBus.Management
{
	[DataContract(Name="CertificateInfo", Namespace="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect")]
	public class FarmCertificateInfo
	{
		[DataMember]
		public string CertificateKeyName
		{
			get;
			set;
		}

		[DataMember]
		public string CertificateName
		{
			get;
			set;
		}

		[DataMember]
		public Microsoft.ServiceBus.Management.CertificateType CertificateType
		{
			get;
			set;
		}

		[DataMember]
		public bool Downloadable
		{
			get;
			set;
		}

		[DataMember]
		public string ExpirationDate
		{
			get;
			set;
		}

		[DataMember]
		public bool IsAutoGenerated
		{
			get;
			set;
		}

		[DataMember]
		public string Thumbprint
		{
			get;
			set;
		}

		public FarmCertificateInfo()
		{
		}
	}
}